"""Marker vocabularies for content-based classification.

These are **heuristics over attacker-influenceable text**, and they drift as
parking providers change their templates. Two consequences shape this module:

* Every marker is deliberately specific. A loose pattern (a bare "404", the word
  "sale") fires on ordinary pages and would mark live sites dead — the most
  damaging error this tool can make, because the operator acts on it.
* Nothing here is a verdict on its own. `rules.py` requires corroboration and
  records which markers fired, so a wrong call can be traced to the rule that
  made it rather than argued about.

Because verdicts are versioned and stored separately from observations,
tightening a list here is a `CLASSIFIER_VERSION` bump plus a re-classify pass —
no refetching, and the old verdicts stay on record for comparison.
"""

from __future__ import annotations

# Hosts and scripts that identify a parking provider outright. These are strong:
# a page served from one of these is parked, whatever else it says.
PARKING_PROVIDERS = (
    "sedoparking.com",
    "sedo.com/search/",
    "parkingcrew.net",
    "bodis.com",
    "parklogic.com",
    "above.com/park",
    "voodoo.com",
    "dan.com",
    "afternic.com",
    "hugedomains.com",
    "namebright.com",
    "undeveloped.com",
    "parked-content.godaddy.com",
    "sav.com/park",
    "domainparkingserver",
    "cashparking.com",
)

# Phrases parking pages use about themselves. Strong, but phrased tightly enough
# not to fire on an article *about* domain parking.
PARKING_PHRASES = (
    "this domain is parked",
    "this domain name is parked",
    "parked free, courtesy of",
    "domain parking service",
    "this webpage was generated by the domain owner",
    "the domain has been registered",
    "this page is provided courtesy of",
)

# Sale intent. Combined with a parking signal this yields `for_sale`, which is
# the highest-value classification the crawler alone can reach.
FOR_SALE_PHRASES = (
    "this domain is for sale",
    "this domain name is for sale",
    "buy this domain",
    "purchase this domain",
    "the domain name is for sale",
    "domain is available for purchase",
    "inquire about this domain",
    "make an offer on this domain",
    "interested in this domain",
    "this domain may be for sale",
)

# Weak on their own — a real page can say "related searches". Only counted when
# a stronger parking signal is already present.
PARKING_WEAK = (
    "related searches",
    "sponsored listings",
    "related links",
    "search ads",
)

# Soft-404 phrasing. Checked against the title and the evidence blob.
SOFT_404_PHRASES = (
    "page not found",
    "page cannot be found",
    "page could not be found",
    "page doesn't exist",
    "page does not exist",
    "the requested url was not found",
    "no longer available",
    "this page has moved",
    "404 error",
    "error 404",
    "http 404",
    "file not found",
    "sorry, we couldn't find",
    "sorry, this page",
    "we can't find the page",
    "content not found",
    "nothing found",
)

# Title markers. A title is far more reliable than body text — a page titled
# "404" almost certainly is one, whereas "404" in a body could be a street
# number, a model number, or a phone extension.
#
# Bare "error" and "oops" were here and had to go: they matched real titles like
# "Standard Error in Statistics" and "Trial and Error", marking live pages dead.
# That is the most damaging mistake this classifier can make, because the
# operator acts on it — so a marker only earns its place if it is implausible in
# a genuine page title.
SOFT_404_TITLE_MARKERS = (
    "404",
    "not found",
    "page missing",
    "page unavailable",
    "page removed",
)

# Below this, a 200 response carries essentially no content. Supporting evidence
# only: a legitimately tiny page exists (a redirect stub, an API root).
THIN_BODY_BYTES = 512


def _haystack(*parts: str | None) -> str:
    return " ".join(p.lower() for p in parts if p)


def find(text: str, needles: tuple[str, ...]) -> list[str]:
    """Every needle present in `text`. Returned, not counted, so the caller can
    record *which* markers fired — a bare score is unauditable."""
    return [n for n in needles if n in text]


def parking_signals(title: str | None, body: str | None) -> tuple[list[str], list[str]]:
    """(strong, weak) parking markers found."""
    text = _haystack(title, body)
    strong = find(text, PARKING_PROVIDERS) + find(text, PARKING_PHRASES)
    weak = find(text, PARKING_WEAK)
    return strong, weak


def for_sale_signals(title: str | None, body: str | None) -> list[str]:
    return find(_haystack(title, body), FOR_SALE_PHRASES)


def soft_404_signals(title: str | None, body: str | None) -> tuple[list[str], list[str]]:
    """(title markers, body phrases) suggesting a not-found page served as 200."""
    title_hits = find((title or "").lower(), SOFT_404_TITLE_MARKERS)
    body_hits = find(_haystack(body), SOFT_404_PHRASES)
    return title_hits, body_hits
